create user dest_schema identified by myOracle0328;
GRANT CREATE SESSION TO dest_schema;
GRANT CREATE TABLE TO dest_schema;
GRANT CREATE VIEW TO dest_schema;
GRANT CREATE SEQUENCE TO dest_schema;
GRANT CREATE PROCEDURE TO dest_schema;
GRANT CREATE TRIGGER TO dest_schema;
GRANT CREATE ANY CONTEXT TO dest_schema;
GRANT CREATE JOB TO dest_schema;
ALTER USER dest_schema quota 100M on USERS;
