create user orig_schema identified by myOracle0328;
GRANT CREATE SESSION TO orig_schema;
GRANT CREATE TABLE TO orig_schema;
GRANT CREATE VIEW TO orig_schema;
GRANT CREATE SEQUENCE TO orig_schema;
GRANT CREATE PROCEDURE TO orig_schema;
GRANT CREATE TRIGGER TO orig_schema;
GRANT CREATE ANY CONTEXT TO orig_schema;
GRANT CREATE JOB TO orig_schema;
ALTER USER orig_schema quota 100M on USERS;
