-- create tables
create table employees (
    id                             number generated by default on null as identity 
                                   constraint employees_id_pk primary key,
    department_id                  number
                                   constraint employees_department_id_fk
                                   references departments on delete cascade,
    name                           varchar2(50 char) not null,
    email                          varchar2(255 char),
    cost_center                    number,
    date_hired                     date,
    job                            varchar2(255 char)
)
;

-- table index
-- create index employees_i1 on employees (department_id);


-- triggers
-- create or replace trigger employees_biu
--     before insert or update 
--     on employees
--     for each row
-- begin
--     :new.email := lower(:new.email);
-- end employees_biu;
-- /