-- create tables
create table departments (
    id                             number generated by default on null as identity 
                                   constraint departments_id_pk primary key,
    name                           varchar2(255 char) not null,
    location                       varchar2(4000 char),
    country                        varchar2(4000 char)
)
;

-- load data
 
insert into departments (
    id,
    name,
    location,
    country
) values (
    1,
    'Budget Compliance',
    'Tanquecitos',
    'United States'
);

insert into departments (
    id,
    name,
    location,
    country
) values (
    2,
    'Operations',
    'Sugarloaf',
    'United States'
);

insert into departments (
    id,
    name,
    location,
    country
) values (
    3,
    'Data Lifecycle Management',
    'Dale City',
    'United States'
);

insert into departments (
    id,
    name,
    location,
    country
) values (
    4,
    'Internal Systems',
    'Grosvenor',
    'United States'
);

commit;

alter table departments
modify id generated always as identity restart start with 5;