-- create tables
create table employees (
    id                             number generated by default on null as identity 
                                   constraint employees_id_pk primary key,
    department_id                  number
                                   constraint employees_department_id_fk
                                   references departments on delete cascade,
    name                           varchar2(50 char) not null,
    email                          varchar2(255 char),
    cost_center                    number,
    date_hired                     date,
    job                            varchar2(255 char)
)
;

-- table index
create index employees_i1 on employees (department_id);


-- triggers
create or replace trigger employees_biu
    before insert or update 
    on employees
    for each row
begin
    :new.email := lower(:new.email);
end employees_biu;
/



-- load data
 

 
-- load data
 
insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    1,
    1,
    'Gricelda Luebbers',
    'gricelda.luebbers@aaab.com',
    46,
    sysdate - 72,
    'Engineer'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    2,
    3,
    'Dean Bollich',
    'dean.bollich@aaac.com',
    76,
    sysdate - 55,
    'Vice President'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    3,
    1,
    'Milo Manoni',
    'milo.manoni@aaad.com',
    95,
    sysdate - 44,
    'Operations Manager'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    4,
    1,
    'Laurice Karl',
    'laurice.karl@aaae.com',
    16,
    sysdate - 56,
    'Business Development Manager'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    5,
    1,
    'August Rupel',
    'august.rupel@aaaf.com',
    41,
    sysdate - 82,
    'Cloud Architect'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    6,
    2,
    'Salome Guisti',
    'salome.guisti@aaag.com',
    83,
    sysdate - 16,
    'HR Representitive'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    7,
    2,
    'Lovie Ritacco',
    'lovie.ritacco@aaah.com',
    91,
    sysdate - 36,
    'User Experience Manager'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    8,
    2,
    'Chaya Greczkowski',
    'chaya.greczkowski@aaai.com',
    22,
    sysdate - 8,
    'Help Desk Specialist'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    9,
    3,
    'Twila Coolbeth',
    'twila.coolbeth@aaaj.com',
    39,
    sysdate - 43,
    'Analyst'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    10,
    3,
    'Carlotta Achenbach',
    'carlotta.achenbach@aaak.com',
    27,
    sysdate - 40,
    'Sales Executive'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    11,
    3,
    'Jeraldine Audet',
    'jeraldine.audet@aaal.com',
    15,
    sysdate - 2,
    'Quality Assurance Analyst'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    12,
    4,
    'August Arouri',
    'august.arouri@aaam.com',
    61,
    sysdate - 3,
    'Facilities Manager'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    13,
    4,
    'Ward Stepney',
    'ward.stepney@aaan.com',
    14,
    sysdate - 62,
    'Legal Assistant'
);

insert into employees (
    id,
    department_id,
    name,
    email,
    cost_center,
    date_hired,
    job
) values (
    14,
    1,
    'Ayana Barkhurst',
    'ayana.barkhurst@aaao.com',
    84,
    sysdate - 16,
    'Application Developer'
);

commit;

alter table employees
modify id generated always as identity restart start with 15;